{% set version = "0.3.14" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-adehabitatma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adehabitatMA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adehabitatMA/adehabitatMA_{{ version }}.tar.gz
  sha256: 3e22a35b34836030871c212286765791d2b1d56befac325a05075f0e5e7ad851

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-filehash
    - r-sp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-filehash
    - r-sp

test:
  commands:
    - $R -e "library('adehabitatMA')"           # [not win]
    - "\"%R%\" -e \"library('adehabitatMA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=adehabitatMA
  license: GPL (>= 2)
  summary: A collection of tools to deal with raster maps.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: adehabitatMA
# Version: 0.3.13
# Date: 2019-04-07
# Depends: R (>= 2.10.0), sp, methods
# Suggests: maptools, tkrplot, MASS
# Imports: utils, graphics, grDevices, stats, filehash
# Title: Tools to Deal with Raster Maps
# Author: Clement Calenge, contributions from Mathieu Basille
# Maintainer: Clement Calenge <clement.calenge@oncfs.gouv.fr>
# Description: A collection of tools to deal with raster maps.
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-04-07 15:54:40 UTC; calenge
# Repository: CRAN
# Date/Publication: 2019-04-07 16:52:50 UTC
